'use client'

import { useState } from 'react'

const jobs = ['Senior Product Designer', 'Specjalista ds. automatyzacji AI', 'Koordynator projektów']

export default function PanelPage() {
  const [active, setActive] = useState('Przegląd')
  return <main className="dashboard-shell"><aside className="dashboard-sidebar"><a className="brand" href="/"><span className="brand-mark">✦</span><span>praca<span>flow</span></span></a><p className="dashboard-label">MENU GŁÓWNE</p>{['Przegląd', 'Oferty dla Ciebie', 'Moje CV', 'Zapisane', 'Moje zlecenia'].map((item) => <button key={item} className={active === item ? 'dashboard-nav active' : 'dashboard-nav'} onClick={() => setActive(item)}>{item}</button>)}<p className="dashboard-label">KONTO</p><button className="dashboard-nav">Ustawienia</button><a className="dashboard-nav" href="/">Wyloguj się</a></aside><section className="dashboard-content"><header className="dashboard-header"><div><span className="section-kicker">PANEL KANDYDATA</span><h1>Dzień dobry, Aleksandro.</h1><p>Oto możliwości dopasowane do Twojego profilu.</p></div><a className="profile-chip" href="/kreator-cv">AK <span>▾</span></a></header><div className="dashboard-grid"><article className="dashboard-card match-overview"><div><span className="mini-label">TWOJE DOPASOWANIE</span><strong>87<span>%</span></strong><p>Twój profil jest gotowy na nowe możliwości.</p></div><div className="circle-progress">87%</div><a href="/kreator-cv">Ulepsz profil →</a></article><article className="dashboard-card stat-card"><span className="mini-label">NOWE OFERTY</span><strong>24</strong><p>oferty dopasowane w tym tygodniu</p><a href="/oferty">Zobacz oferty →</a></article><article className="dashboard-card stat-card"><span className="mini-label">PROFIL CV</span><strong>72<span>%</span></strong><p>kompletności profilu</p><a href="/kreator-cv">Dokończ CV →</a></article></div><section className="dashboard-card offers-card" id="offers"><div className="dashboard-section-head"><div><span className="section-kicker">REKOMENDOWANE DLA CIEBIE</span><h2>Oferty pracy</h2></div><a href="/oferty">Zobacz wszystkie →</a></div>{jobs.map((job, index) => <div className="dashboard-job" key={job}><span className="company-badge">{['N', 'O', 'P'][index]}</span><div><strong>{job}</strong><p>{['Northstar Labs · Warszawa · hybrydowo', 'Orbital Systems · Zdalnie · Polska', 'Pracownia Forma · Kraków · stacjonarnie'][index]}</p></div><b>{96 - index * 5}%</b><button aria-label={`Zapisz ${job}`}>♡</button></div>)}</section></section></main>
}
