'use client'

import { useMemo, useState } from 'react'

const jobs = [
  { title: 'Senior Product Designer', company: 'Northstar Labs', place: 'Warszawa · hybrydowo', salary: '18 000–24 000 zł', match: 96, tag: 'Design' },
  { title: 'Specjalista ds. automatyzacji AI', company: 'Orbital Systems', place: 'Zdalnie · Polska', salary: '14 000–19 000 zł', match: 91, tag: 'AI / Tech' },
  { title: 'Koordynator projektów', company: 'Pracownia Forma', place: 'Kraków · stacjonarnie', salary: '9 000–12 000 zł', match: 84, tag: 'Operacje' },
]

export default function Home() {
  const [activeTab, setActiveTab] = useState('Kandydat')
  const [query, setQuery] = useState('')
  const [location, setLocation] = useState('Polska')
  const [salary, setSalary] = useState('')
  const [contract, setContract] = useState('')
  const [remote, setRemote] = useState(false)
  const [liveJobs, setLiveJobs] = useState<typeof jobs | null>(null)
  const [jobsLoading, setJobsLoading] = useState(false)
  const [searchError, setSearchError] = useState('')
  const filteredJobs = useMemo(() => (liveJobs ?? jobs).filter((job) => `${job.title} ${job.company} ${job.tag} ${job.place} ${job.salary}`.toLowerCase().includes(query.toLowerCase())), [query, liveJobs])

  const searchJobs = async (value = query) => {
    setQuery(value)
    if (value.trim().length < 2 && location.trim().length < 2) {
      setLiveJobs(null)
      return
    }
    setJobsLoading(true)
    setSearchError('')
    try {
      const params = new URLSearchParams({ keywords: value.trim() || 'praca', location: location.trim() || 'Polska' })
      if (salary) params.set('salary', salary)
      if (contract) params.set('contract', contract)
      if (remote) params.set('remote', 'true')
      const response = await fetch(`/api/jobs?${params.toString()}`)
      const data = await response.json()
      if (!response.ok) throw new Error(data.error || 'Nie udało się pobrać ofert.')
      setLiveJobs((data.jobs ?? []).slice(0, 8).map((job: { title?: string; company?: string; location?: string; salary?: string; type?: string }) => ({
        title: job.title || 'Oferta pracy', company: job.company || 'Pracodawca', place: job.location || location || 'Polska',
        salary: job.salary || 'Sprawdź w ogłoszeniu', match: 0, tag: job.type || 'Oferta pracy',
      })))
    } catch (error) {
      setSearchError(error instanceof Error ? error.message : 'Wyszukiwanie jest chwilowo niedostępne.')
    } finally {
      setJobsLoading(false)
    }
  }

  return (
    <main className="site-shell">
      <nav className="nav container"><a className="brand" href="#top" aria-label="PracaFlow strona główna"><span className="brand-mark">✦</span><span>praca<span>flow</span></span></a><div className="nav-links"><a href="#jobs">Oferty pracy</a><a href="/zlecenia">Zlecenia</a><a href="/kreator-cv">Kreator CV</a><a href="/rekruter">Dla rekruterów</a></div><div className="nav-actions"><a className="login-link" href="/logowanie">Zaloguj się</a><a className="button button-small" href="/rejestracja">Załóż konto <span>↗</span></a></div></nav>
      <section className="hero container" id="top"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot" /> Nowa generacja rynku pracy w Polsce</div><h1>Praca, która<br /><em>pasuje</em> do Ciebie.</h1><p>Łączymy ludzi z możliwościami. Inteligentne dopasowanie ofert, kreator CV i przestrzeń dla tych, którzy chcą zatrudniać lepiej.</p><div className="hero-buttons"><a className="button" href="#explore">Znajdź swoją pracę <span>↗</span></a><a className="text-link" href="#recruiter">Jesteś rekruterem? <span>Dowiedz się więcej →</span></a></div><div className="trust-row"><div className="avatars"><span>AK</span><span>MN</span><span>JD</span><span>+</span></div><p><strong>12 000+</strong> osób znalazło<br />swoją kolejną możliwość</p></div></div><div className="hero-visual" aria-label="Podgląd dopasowania oferty do profilu"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="match-card glass-card"><div className="card-top"><span className="mini-label">AI MATCH</span><span className="live-label"><span className="pulse-dot" /> LIVE</span></div><div className="match-score">94<span>%</span></div><p>Idealne dopasowanie</p><div className="match-bar"><span /></div><div className="match-meta"><span>Senior UX Designer</span><span>Warszawa · hybrydowo</span></div><div className="match-footer"><span>Northstar Labs</span><b>18–24k PLN</b></div></div><div className="floating-card floating-top">PROFIL ZWERYFIKOWANY <strong>✓</strong></div><div className="floating-card floating-bottom"><span className="spark">✦</span><span><strong>3 nowe oferty</strong><br />dopasowane do Ciebie</span></div></div></section>
      <section className="ticker"><div className="ticker-track">TECHNOLOGIA <span>✦</span> FINANSE <span>✦</span> MARKETING <span>✦</span> DESIGN <span>✦</span> INŻYNIERIA <span>✦</span> SPRZEDAŻ <span>✦</span> EDUKACJA <span>✦</span> TECHNOLOGIA <span>✦</span></div></section>
      <section className="section container" id="explore"><div className="section-heading"><div><span className="section-kicker">ODKRYJ MOŻLIWOŚCI</span><h2>Nie szukaj pracy.<br /><span>Znajdź swoje miejsce.</span></h2></div><p>Algorytm, który rozumie więcej niż słowa kluczowe. Twoje doświadczenie, ambicje i sposób pracy — wszystko ma znaczenie.</p></div><div className="tabs"><button className={activeTab === 'Kandydat' ? 'tab active' : 'tab'} onClick={() => setActiveTab('Kandydat')}>Dla kandydatów</button><button className={activeTab === 'Rekruter' ? 'tab active' : 'tab'} onClick={() => setActiveTab('Rekruter')}>Dla rekruterów</button></div>{activeTab === 'Kandydat' ? <div className="feature-grid"><article className="feature-card feature-large"><div className="feature-icon">⌁</div><h3>Dopasowanie,<br /><span>które działa.</span></h3><p>AI analizuje Twój profil i dostarcza oferty, które naprawdę mają sens. Bez spamu, bez przypadkowych wyników.</p><a href="#jobs">Przeglądaj oferty <span>↗</span></a><div className="mini-job"><span className="mini-logo">N</span><span><strong>Product Designer</strong><small>Northstar Labs · 94% match</small></span><b>→</b></div></article><article className="feature-card feature-dark" id="cv"><div className="feature-icon lime">✦</div><h3>Twoje CV.<br /><span>Twoja przewaga.</span></h3><p>Stwórz CV, które opowiada Twoją historię. Profesjonalnie, szybko, po Twojemu.</p><a href="#pricing">Otwórz kreator CV <span>↗</span></a><div className="cv-preview"><div className="cv-line short" /><div className="cv-line" /><div className="cv-line" /><div className="cv-line short" /></div></article><article className="feature-card feature-accent" id="gigs"><div className="feature-icon">↗</div><h3>Więcej niż<br /><span>etat.</span></h3><p>Korepetycje, usługi i zlecenia. Zamień swoje umiejętności w możliwości.</p><a href="#jobs">Przeglądaj zlecenia <span>↗</span></a></article></div> : <div className="recruiter-panel" id="recruiter"><div><span className="section-kicker">PANEL REKRUTERA</span><h3>Zatrudniaj ludzi,<br /><span>nie słowa kluczowe.</span></h3><p>Przeszukuj bazę zweryfikowanych CV, publikuj oferty i korzystaj z dopasowania AI.</p><a className="button" href="#pricing">Zobacz pakiet rekrutera <span>↗</span></a></div><div className="recruiter-stats"><div><strong>24k</strong><span>aktywnych profili</span></div><div><strong>87%</strong><span>trafności dopasowań</span></div><div><strong>3.2×</strong><span>szybsza rekrutacja</span></div></div></div>}</section>
      <section className="jobs-section" id="jobs"><div className="container"><div className="section-heading jobs-heading"><div><span className="section-kicker">NAJNOWSZE MOŻLIWOŚCI</span><h2>Oferty stworzone<br /><span>dla Ciebie.</span></h2></div><div className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') searchJobs() }} placeholder="Stanowisko, umiejętność lub firma..." aria-label="Szukaj stanowiska, umiejętności lub firmy" /><button type="button" className="search-submit" onClick={() => searchJobs()} disabled={jobsLoading}>{jobsLoading ? 'Szukam...' : 'Szukaj'}</button></div><div className="search-filters"><input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Lokalizacja" aria-label="Lokalizacja" /><select value={salary} onChange={(event) => setSalary(event.target.value)} aria-label="Minimalne wynagrodzenie"><option value="">Dowolne zarobki</option><option value="5000">Od 5 000 zł</option><option value="10000">Od 10 000 zł</option><option value="15000">Od 15 000 zł</option></select><select value={contract} onChange={(event) => setContract(event.target.value)} aria-label="Rodzaj umowy"><option value="">Każda umowa</option><option value="umowa o pracę">Umowa o pracę</option><option value="b2b">B2B</option><option value="umowa zlecenie">Umowa zlecenie</option></select><label className="remote-filter"><input type="checkbox" checked={remote} onChange={(event) => setRemote(event.target.checked)} /> Zdalnie</label></div>{searchError && <p className="search-error" role="alert">{searchError}</p>}</div><div className="job-list">{filteredJobs.map((job) => <article className="job-row" key={job.title}><div className="company-badge">{job.company.slice(0, 1)}</div><div className="job-main"><div className="job-title-row"><h3>{job.title}</h3><span className="job-tag">{job.tag}</span></div><p>{job.company} <span>·</span> {job.place}</p></div><div className="job-match"><strong>{job.match}%</strong><span>dopasowanie</span></div><div className="job-salary">{job.salary}<span>miesięcznie</span></div><button className="arrow-button" aria-label={`Zobacz ofertę ${job.title}`}>↗</button></article>)}</div><a className="center-link" href="#all-jobs">Zobacz wszystkie oferty <span>→</span></a></div></section>
      <section className="pricing-section container" id="pricing"><div className="section-heading"><div><span className="section-kicker">PROSTY MODEL</span><h2>Ty wybierasz<br /><span>jak działasz.</span></h2></div><p>Zacznij bez zobowiązań. Płać tylko za funkcje, których potrzebujesz — bez ukrytych kosztów.</p></div><div className="pricing-grid"><article className="price-card"><span className="price-label">DLA KANDYDATÓW</span><h3>Start</h3><p>Wszystko, czego potrzebujesz, żeby zacząć.</p><div className="price">0 <small>zł</small></div><a className="button button-outline" href="#start">Załóż konto <span>↗</span></a><ul><li>Przeglądanie ofert pracy i zleceń</li><li>Profil kandydata</li><li>Personalizowane rekomendacje</li></ul></article><article className="price-card featured-price"><span className="price-label">NAJPOPULARNIEJSZY</span><h3>Kreator CV</h3><p>CV, które otwiera właściwe drzwi.</p><div className="price">14,99 <small>zł <br />jednorazowo</small></div><a className="button" href="#cv">Stwórz swoje CV <span>↗</span></a><ul><li>Profesjonalne szablony CV</li><li>Analiza CV przez AI</li><li>Eksport PDF i widoczność w bazie</li></ul></article><article className="price-card recruiter-price"><span className="price-label">DLA REKRUTERÓW</span><h3>Recruiter Pro</h3><p>Pełny dostęp do talentów.</p><div className="price">199 <small>zł <br />miesięcznie</small></div><a className="button button-dark" href="#recruiter">Zatrudniaj lepiej <span>↗</span></a><ul><li>Baza CV i wyszukiwanie AI</li><li>Nielimitowane przeglądanie profili</li><li>Publikacja ofert w cenie</li></ul></article></div><p className="oneoff-note">Publikacja ogłoszenia lub zlecenia: <strong>9,99 zł</strong> · Wyróżnienie: <strong>29,99 zł</strong></p></section>
      <footer className="footer"><div className="container"><div className="footer-top"><div><a className="brand" href="#top"><span className="brand-mark">✦</span><span>praca<span>flow</span></span></a><p>Rynek pracy, który<br />pracuje dla Ciebie.</p></div><div className="footer-links"><div><strong>Platforma</strong><a href="#jobs">Oferty pracy</a><a href="/zlecenia">Zlecenia</a><a href="/kreator-cv">Kreator CV</a><a href="/rekruter">Dla rekruterów</a></div><div><strong>Informacje</strong><a href="/informacje">O nas</a><a href="/blog">Blog</a><a href="/faq">FAQ</a><a href="/kontakt">Kontakt</a></div><div><strong>Legal</strong><a href="/polityka-prywatnosci">Polityka prywatności</a><a href="/regulamin">Regulamin</a><a href="/rodo">RODO</a><a href="/cookies">Cookies</a></div></div></div><div className="footer-bottom"><span>© 2026 pracaflow. Wszystkie prawa zastrzeżone.</span><div className="socials"><a href="#linkedin" aria-label="LinkedIn">in</a><a href="#instagram" aria-label="Instagram">ig</a><a href="#facebook" aria-label="Facebook">f</a></div><span>Made for people with ambition.</span></div></div></footer>
    </main>
  )
}
