'use client'

import { useMemo, useState } from 'react'

const jobs = [
  { slug: 'spawacz', title: 'Spawacz', company: 'MetalWorks Polska', place: 'Katowice · stacjonarnie', salary: '8 000–12 000 zł', match: 94, tag: 'Produkcja' },
  { slug: 'senior-product-designer', title: 'Senior Product Designer', company: 'Northstar Labs', place: 'Warszawa · hybrydowo', salary: '18 000–24 000 zł', match: 96, tag: 'Design' },
  { slug: 'specjalista-automatyzacji-ai', title: 'Specjalista ds. automatyzacji AI', company: 'Orbital Systems', place: 'Zdalnie · Polska', salary: '14 000–19 000 zł', match: 91, tag: 'AI / Tech' },
  { slug: 'koordynator-projektow', title: 'Koordynator projektów', company: 'Pracownia Forma', place: 'Kraków · stacjonarnie', salary: '9 000–12 000 zł', match: 84, tag: 'Operacje' },
]

export default function Home() {
  const [activeTab, setActiveTab] = useState('Kandydat')
  const [query, setQuery] = useState('')
  const filteredJobs = useMemo(() => jobs.filter((job) => `${job.title} ${job.company} ${job.tag}`.toLowerCase().includes(query.toLowerCase())), [query])
  return <main className="site-shell">
    <nav className="nav container"><a className="brand" href="/" aria-label="pracaflow strona główna"><span className="brand-mark">✦</span><span>praca<span>flow</span></span></a><div className="nav-links"><a href="/oferty">Oferty pracy</a><a href="/oferty?type=zlecenia">Zlecenia</a><a href="/kreator-cv">Kreator CV</a><a href="/rekruter">Dla rekruterów</a></div><div className="nav-actions"><a className="login-link" href="/sign-in">Zaloguj się</a><a className="button button-small" href="/rejestracja">Załóż konto <span>↗</span></a></div></nav>
    <section className="hero container" id="top"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot" /> Nowa generacja rynku pracy w Polsce</div><h1>Praca, która<br /><em>pasuje</em> do Ciebie.</h1><p>Łączymy ludzi z możliwościami. Inteligentne dopasowanie ofert, kreator CV i przestrzeń dla tych, którzy chcą zatrudniać lepiej.</p><div className="hero-buttons"><a className="button" href="/oferty">Znajdź swoją pracę <span>↗</span></a><a className="text-link" href="/rekruter">Jesteś rekruterem? <span>Dowiedz się więcej →</span></a></div><div className="trust-row"><div className="avatars"><span>AK</span><span>MN</span><span>JD</span><span>+</span></div><p><strong>12 000+</strong> osób znalazło<br />swoją kolejną możliwość</p></div></div><div className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="match-card glass-card"><div className="card-top"><span className="mini-label">AI MATCH</span><span className="live-label"><span className="pulse-dot" /> LIVE</span></div><div className="match-score">94<span>%</span></div><p>Idealne dopasowanie</p><div className="match-bar"><span /></div><div className="match-meta"><span>Senior UX Designer</span><span>Warszawa · hybrydowo</span></div><div className="match-footer"><span>Northstar Labs</span><b>18–24k PLN</b></div></div><div className="floating-card floating-top">PROFIL ZWERYFIKOWANY <strong>✓</strong></div><div className="floating-card floating-bottom"><span className="spark">✦</span><span><strong>3 nowe oferty</strong><br />dopasowane do Ciebie</span></div></div></section>
    <section className="ticker"><div className="ticker-track">TECHNOLOGIA <span>✦</span> FINANSE <span>✦</span> MARKETING <span>✦</span> DESIGN <span>✦</span> INŻYNIERIA <span>✦</span> SPRZEDAŻ <span>✦</span> EDUKACJA <span>✦</span></div></section>
    <section className="section container" id="explore"><div className="section-heading"><div><span className="section-kicker">ODKRYJ MOŻLIWOŚCI</span><h2>Nie szukaj pracy.<br /><span>Znajdź swoje miejsce.</span></h2></div><p>Algorytm, który rozumie więcej niż słowa kluczowe. Twoje doświadczenie, ambicje i sposób pracy — wszystko ma znaczenie.</p></div><div className="tabs"><button className={activeTab === 'Kandydat' ? 'tab active' : 'tab'} onClick={() => setActiveTab('Kandydat')}>Dla kandydatów</button><button className={activeTab === 'Rekruter' ? 'tab active' : 'tab'} onClick={() => setActiveTab('Rekruter')}>Dla rekruterów</button></div>{activeTab === 'Kandydat' ? <div className="feature-grid"><article className="feature-card feature-large"><div className="feature-icon">⌁</div><h3>Dopasowanie,<br /><span>które działa.</span></h3><p>AI analizuje Twój profil i dostarcza oferty, które naprawdę mają sens.</p><a href="/oferty">Przeglądaj oferty <span>↗</span></a><div className="mini-job"><span className="mini-logo">N</span><span><strong>Product Designer</strong><small>Northstar Labs · 94% match</small></span><b>→</b></div></article><article className="feature-card feature-dark"><div className="feature-icon lime">✦</div><h3>Twoje CV.<br /><span>Twoja przewaga.</span></h3><p>Stwórz CV, które opowiada Twoją historię. Profesjonalnie, szybko, po Twojemu.</p><a href="/kreator-cv">Otwórz kreator CV <span>↗</span></a><div className="cv-preview"><div className="cv-line short" /><div className="cv-line" /><div className="cv-line" /><div className="cv-line short" /></div></article><article className="feature-card feature-accent"><div className="feature-icon">↗</div><h3>Więcej niż<br /><span>etat.</span></h3><p>Korepetycje, usługi i zlecenia. Zamień swoje umiejętności w możliwości.</p><a href="/oferty?type=zlecenia">Przeglądaj zlecenia <span>↗</span></a></article></div> : <div className="recruiter-panel"><div><span className="section-kicker">DLA FIRM</span><h3>Talenty, które<br /><span>robią różnicę.</span></h3><p>Publikuj oferty, przeszukuj profile i docieraj do osób, które pasują nie tylko na papierze.</p><a className="button" href="/rekruter">Otwórz panel rekrutera <span>↗</span></a></div><div className="recruiter-stats"><div><strong>94%</strong><span>trafności<br />dopasowania</span></div><div><strong>3×</strong><span>szybsza<br />rekrutacja</span></div><div><strong>12k</strong><span>aktywnych<br />profili</span></div></div></div>}</section>
    <section className="jobs-section" id="jobs"><div className="container"><div className="section-heading jobs-heading"><div><span className="section-kicker">NAJNOWSZE MOŻLIWOŚCI</span><h2>Oferty stworzone<br /><span>dla Ciebie.</span></h2></div><div className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Szukaj stanowiska, firmy..." aria-label="Szukaj ofert" /><kbd>⌘ K</kbd></div></div><div className="job-list">{filteredJobs.map((job) => <a className="job-row" href={`/${job.slug}`} key={job.slug}><div className="company-badge">{job.company.slice(0, 1)}</div><div className="job-main"><div className="job-title-row"><h3>{job.title}</h3><span className="job-tag">{job.tag}</span></div><p>{job.company} <span>·</span> {job.place}</p></div><div className="job-match"><strong>{job.match}%</strong><span>dopasowanie</span></div><div className="job-salary">{job.salary}<span>miesięcznie</span></div><span className="arrow-button" aria-hidden="true">↗</span></a>)}</div><a className="center-link" href="/oferty">Zobacz wszystkie oferty <span>→</span></a></div></section>
    <section className="pricing-section container"><div className="section-heading"><div><span className="section-kicker">PROSTY MODEL</span><h2>Ty wybierasz<br /><span>jak działasz.</span></h2></div><p>Zacznij bez zobowiązań. Płać tylko za funkcje, których potrzebujesz.</p></div><div className="pricing-grid"><article className="price-card"><span className="price-label">DLA KANDYDATÓW</span><h3>Start</h3><p>Wszystko, czego potrzebujesz, żeby zacząć.</p><div className="price">0 <small>zł</small></div><a className="button button-outline" href="/panel">Załóż konto <span>↗</span></a></article><article className="price-card featured-price"><span className="price-label">NAJPOPULARNIEJSZY</span><h3>Kreator CV</h3><p>CV, które otwiera właściwe drzwi.</p><div className="price">14,99 <small>zł jednorazowo</small></div><a className="button" href="/kreator-cv">Stwórz swoje CV <span>↗</span></a></article><article className="price-card recruiter-price"><span className="price-label">DLA REKRUTERÓW</span><h3>Recruiter Pro</h3><p>Pełny dostęp do talentów.</p><div className="price">199 <small>zł miesięcznie</small></div><a className="button button-dark" href="/rekruter">Zatrudniaj lepiej <span>↗</span></a></article></div></section>
    <footer className="footer"><div className="container"><div className="footer-top"><div><a className="brand" href="/"><span className="brand-mark">✦</span><span>praca<span>flow</span></span></a><p>Rynek pracy, który<br />pracuje dla Ciebie.</p></div><div className="footer-links"><div><strong>Platforma</strong><a href="/oferty">Oferty pracy</a><a href="/oferty?type=zlecenia">Zlecenia</a><a href="/kreator-cv">Kreator CV</a><a href="/rekruter">Dla rekruterów</a></div><div><strong>Informacje</strong><a href="/informacje">O nas i FAQ</a><a href="/informacje">Kontakt</a></div><div><strong>Legal</strong><a href="/polityka-prywatnosci">Polityka prywatności</a><a href="/regulamin">Regulamin</a><a href="/rodo">RODO</a><a href="/cookies">Cookies</a></div></div></div><div className="footer-bottom"><span>© 2026 pracaflow. Wszystkie prawa zastrzeżone.</span><span>Made for people with ambition.</span></div></div></footer>
  </main>
}
