'use client'
import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { authClient } from '@/lib/auth-client'

export function AuthForm({ mode }: { mode: 'sign-in' | 'sign-up' }) {
  const router = useRouter(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); const data = new FormData(event.currentTarget); const email = String(data.get('email')); const password = String(data.get('password')); const name = String(data.get('name') || ''); const role = String(data.get('role') || 'candidate'); const result = mode === 'sign-up' ? await authClient.signUp.email({ email, password, name }) : await authClient.signIn.email({ email, password }); if (result.error) setError('Nie udało się wykonać operacji. Sprawdź dane i spróbuj ponownie.'); else { router.push(role === 'recruiter' ? '/rekruter' : '/panel'); router.refresh() } setLoading(false) }
  return <main className="auth-shell"><a className="brand" href="/"><span className="brand-mark">✦</span><span>praca<span>flow</span></span></a><section className="auth-card"><span className="section-kicker">{mode === 'sign-up' ? 'NOWY PROFIL' : 'WITAJ PONOWNIE'}</span><h1>{mode === 'sign-up' ? 'Utwórz konto.' : 'Zaloguj się.'}</h1><p>{mode === 'sign-up' ? 'Zapisuj oferty i buduj swoją ścieżkę kariery.' : 'Wróć do swoich ofert, CV i zapisanych możliwości.'}</p><form onSubmit={submit}>{mode === 'sign-up' && <><label>Imię i nazwisko<input name="name" required /></label><label>Typ konta<select name="role" defaultValue="candidate"><option value="candidate">Konto użytkownika</option><option value="recruiter">Panel rekrutera</option></select></label></>}<label>E-mail<input name="email" type="email" required /></label><label>Hasło<input name="password" type="password" minLength={8} required /></label>{error && <p className="form-error">{error}</p>}<button className="button" disabled={loading}>{loading ? 'Chwila...' : mode === 'sign-up' ? 'Zarejestruj się' : 'Zaloguj się'} <span>↗</span></button></form><p className="auth-switch">{mode === 'sign-up' ? 'Masz już konto?' : 'Nie masz jeszcze konta?'} <a href={mode === 'sign-up' ? '/sign-in' : '/sign-up'}>{mode === 'sign-up' ? 'Zaloguj się' : 'Zarejestruj się'}</a></p></section></main>
}
