'use client'

import { useState } from 'react'

const skillNames = ['Komunikacja', 'Organizacja pracy', 'Praca zespołowa', 'TIG / MAG', 'Język angielski']

export default function CvFormPage() {
  const [saved, setSaved] = useState(false)
  const [levels, setLevels] = useState<Record<string, number>>(() => Object.fromEntries(skillNames.map((skill) => [skill, 3])))
  const [skills, setSkills] = useState(skillNames)
  function setLevel(skill: string, level: number) { setLevels((current) => ({ ...current, [skill]: level })) }
  return <main className="form-page container"><a className="back-link" href="/kreator-cv">← Wróć do kreatora CV</a><span className="section-kicker">KREATOR CV · KROK 1</span><h1>Uzupełnij swoje CV.</h1><p>Dodaj najważniejsze informacje i oceń swoje umiejętności złotymi gwiazdkami.</p>{saved ? <section className="success-state"><h2>CV zostało zapisane.</h2><p>Twój profil jest gotowy do pokazania rekruterom.</p><a className="button" href="/panel">Przejdź do panelu <span>↗</span></a></section> : <form className="publish-form cv-form" onSubmit={(event) => { event.preventDefault(); setSaved(true) }}><fieldset><legend>Dane podstawowe</legend><label>Imię i nazwisko<input required name="name" placeholder="np. Jan Kowalski" /></label><label>Stanowisko<input required name="role" placeholder="np. Spawacz TIG / MAG" /></label><label>Lokalizacja<input required name="location" placeholder="np. Katowice lub zdalnie" /></label><label>E-mail<input required type="email" name="email" placeholder="jan@example.com" /></label></fieldset><fieldset><legend>Umiejętności</legend><p className="fieldset-hint">Wybierz poziom od 1 do 5. Złota gwiazdka oznacza opanowaną umiejętność.</p><div className="skills-list">{skills.map((skill) => <div className="skill-row" key={skill}><span>{skill}</span><div className="star-rating" role="radiogroup" aria-label={`Poziom umiejętności ${skill}`}>{[1, 2, 3, 4, 5].map((star) => <button type="button" key={star} className={star <= levels[skill] ? 'star active' : 'star'} onClick={() => setLevel(skill, star)} aria-label={`${star} z 5`} aria-pressed={star === levels[skill]}>★</button>)}</div><b>{levels[skill]}/5</b></div>)}</div><button type="button" className="text-link add-skill" onClick={() => { const name = `Nowa umiejętność ${skills.length + 1}`; setSkills((current) => [...current, name]); setLevels((current) => ({ ...current, [name]: 1 })) }}>+ Dodaj umiejętność</button></fieldset><fieldset><legend>Doświadczenie i profil</legend><label>O mnie<textarea name="summary" placeholder="Krótko opisz swoje doświadczenie" rows={5} /></label><label>Doświadczenie zawodowe<textarea name="experience" placeholder="Firma, stanowisko, najważniejsze osiągnięcia" rows={5} /></label><label>Wykształcenie<input name="education" placeholder="Szkoła lub kurs" /></label></fieldset><button className="button" type="submit">Zapisz CV <span>↗</span></button></form>}</main>
}
