import { notFound } from 'next/navigation'

const content: Record<string, { eyebrow: string; title: string; intro: string; sections: string[] }> = {
  'polityka-prywatnosci': { eyebrow: 'DOKUMENT PRAWNY', title: 'Polityka prywatności', intro: 'Chronimy Twoje dane i jasno wyjaśniamy, po co ich potrzebujemy.', sections: ['Administratorem danych jest operator platformy pracaflow. Przetwarzamy dane konta, profilu, CV i aktywności wyłącznie w celu świadczenia usług, dopasowania ofert oraz obsługi płatności.', 'CV może być udostępnione rekruterom wyłącznie po świadomej zgodzie użytkownika. Zgodę można wycofać w ustawieniach, a dane usunąć lub wyeksportować.', 'Kontakt w sprawach prywatności: privacy@pracaflow.pl. Dokument będzie uzupełniony o pełne dane administratora przed uruchomieniem produkcyjnym.'] },
  regulamin: { eyebrow: 'DOKUMENT PRAWNY', title: 'Regulamin platformy', intro: 'Zasady korzystania z pracaflow dla kandydatów, zleceniodawców i rekruterów.', sections: ['Konto użytkownika jest osobiste, a informacje publikowane na platformie muszą być prawdziwe i zgodne z prawem.', 'Publikacja ogłoszeń, zleceń i wyróżnień może wymagać opłaty zgodnej z aktualnym cennikiem. Płatności obsługuje zewnętrzny operator.', 'Nie gwarantujemy zatrudnienia ani wykonania zlecenia. Użytkownicy odpowiadają za treść swoich publikacji i komunikację.'] },
  rodo: { eyebrow: 'DANE OSOBOWE', title: 'RODO i Twoje prawa', intro: 'Masz kontrolę nad swoim CV, profilem i zgodami.', sections: ['Przysługuje Ci prawo dostępu, sprostowania, usunięcia, ograniczenia przetwarzania, przenoszenia danych oraz sprzeciwu.', 'Analiza CV przez AI służy rekomendacjom i nie podejmuje samodzielnych decyzji rekrutacyjnych. Wyniki należy traktować jako pomoc, nie wyrok.', 'W sprawach skarg możesz skontaktować się z organem nadzorczym właściwym dla ochrony danych osobowych.'] },
  cookies: { eyebrow: 'TRANSPARENTNOŚĆ', title: 'Polityka cookies', intro: 'Używamy tylko tych plików cookies, które są potrzebne do działania serwisu lub pomagają nam go ulepszać.', sections: ['Cookies niezbędne utrzymują sesję, bezpieczeństwo i preferencje użytkownika.', 'Cookies analityczne są opcjonalne i mogą zostać wyłączone. Nie sprzedajemy danych o aktywności użytkowników.', 'Ustawieniami cookies możesz zarządzać w swojej przeglądarce lub przez panel preferencji na stronie.'] },
}

export default async function LegalPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const page = content[slug]
  if (!page) notFound()
  return <main className="info-shell"><nav className="nav container"><a className="brand" href="/"><span className="brand-mark">✦</span><span>praca<span>flow</span></span></a><a className="button button-small" href="/">Wróć do strony <span>↗</span></a></nav><article className="legal-page container"><span className="section-kicker">{page.eyebrow}</span><h1>{page.title}</h1><p className="legal-intro">{page.intro}</p><div className="legal-sections">{page.sections.map((section, index) => <section key={section}><span>0{index + 1}</span><p>{section}</p></section>)}</div><p className="legal-date">Wersja robocza · wrzesień 2026</p></article></main>
}
